- project:
    templates:
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-pep8
        - ipa-builder-tempest-ironic-inspector-src
    gate:
      jobs:
        - openstack-tox-pep8
        - ipa-builder-tempest-ironic-inspector-src
    post:
      jobs:
        - publish-openstack-python-branch-tarball
        - ipa-builder-buildimage-tinyipa

- job:
    name: ipa-builder-tempest-ironic-inspector-src
    parent: ironic-ipa-base
    timeout: 10800
    required-projects:
      # These are in addition to what is in ironic-ipa-base
      - openstack/ironic-inspector
      - openstack/python-ironic-inspector-client
    vars:
      devstack_localrc:
        DEVSTACK_GATE_TEMPEST_REGEX: InspectorBasicTest
        DEVSTACK_GATE_IRONIC_INSPECTOR: 1
        IRONIC_VM_EPHEMERAL_DISK: 0
        IRONIC_TEMPEST_WHOLE_DISK_IMAGE: True
        IRONIC_INSPECTOR_BUILD_RAMDISK: True
        SWIFT_ENABLE_TEMPURLS: True
        SWIFT_TEMPURL_KEY: secretkey
      devstack_plugins:
        ironic-inspector: https://opendev.org/openstack/ironic-inspector

- job:
    name: ipa-builder-buildimage-tinyipa
    parent: ironic-python-agent-buildimage-base
    vars:
      image_name: 'tinyipa'
