- project:
    templates:
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-pep8
        - ironic-standalone-ipa-src
        - ipa-tempest-partition-bios-ipmi-direct-tinyipa-src
        - ipa-tempest-partition-bios-ipmi-iscsi-tinyipa-src
        - ipa-tempest-wholedisk-bios-ipmi-direct-tinyipa-src
        - ipa-tempest-wholedisk-bios-ipmi-iscsi-tinyipa-src
        - ipa-tempest-ironic-inspector-src
    gate:
      jobs:
        - openstack-tox-pep8
        - ironic-standalone-ipa-src
        - ipa-tempest-partition-bios-ipmi-direct-tinyipa-src
        - ipa-tempest-partition-bios-ipmi-iscsi-tinyipa-src
        - ipa-tempest-wholedisk-bios-ipmi-direct-tinyipa-src
        - ipa-tempest-wholedisk-bios-ipmi-iscsi-tinyipa-src
        - ipa-tempest-ironic-inspector-src
    post:
      jobs:
        - publish-openstack-python-branch-tarball
        - ipa-builder-buildimage-tinyipa

- job:
    name: ipa-builder-buildimage-tinyipa
    parent: ironic-python-agent-buildimage-base
    vars:
      image_name: 'tinyipa'
